#include "TH1F.h"
#include <cmath>
#include <fstream>
#include <stdio.h>
#include <iostream>
#include <string.h>
#include <algorithm>
#include "T3M_common.h"
#include "BDT_optimal_cut.h"

using namespace std;

void BDT_optimal_cut() 
{
    //TString cat_name[] = {"A+B+C"};
    TString cat_name[] = {"A",
                          "B",
                          "C"};
    int n_cat = sizeof(cat_name) / sizeof(cat_name[0]);
    
    for(int k=0; k<n_cat; k++)
    {
  
/*
            //full path of root files generated by TMVA
            TString file_name = "TMVA_"+TMVA_inputpath+cat_name[k]+".root";
	    TFile *f = new TFile(file_name,"READ");

	    TH1F *h_test_signal;
	    TH1F *h_test_bkg;
	    TH1F *h_test_signal2;
	    TH1F *h_test_bkg2;
	    TH1F *h_train_signal2;
	    TH1F *h_train_bkg2;
            //high granularity BDT scores
	    h_test_signal = (TH1F*)f->Get(TMVA_inputpath+cat_name[k]+"/Method_"+method+"/"+method+"/MVA_"+method+"_S_high");
	    h_test_bkg = (TH1F*)f->Get(TMVA_inputpath+cat_name[k]+"/Method_"+method+"/"+method+"/MVA_"+method+"_B_high");
            //Normal binning BDT scores
	    h_test_signal2 = (TH1F*)f->Get(TMVA_inputpath+cat_name[k]+"/Method_"+method+"/"+method+"/MVA_"+method+"_S");
	    h_test_bkg2 = (TH1F*)f->Get(TMVA_inputpath+cat_name[k]+"/Method_"+method+"/"+method+"/MVA_"+method+"_B");
	    h_train_signal2 = (TH1F*)f->Get(TMVA_inputpath+cat_name[k]+"/Method_"+method+"/"+method+"/MVA_"+method+"_Train_S");
	    h_train_bkg2 = (TH1F*)f->Get(TMVA_inputpath+cat_name[k]+"/Method_"+method+"/"+method+"/MVA_"+method+"_Train_B");
            h_test_signal->SetDirectory(0);
            h_test_bkg->SetDirectory(0);
            h_test_signal2->SetDirectory(0);
            h_test_bkg2->SetDirectory(0);
            h_train_signal2->SetDirectory(0);
            h_train_bkg2->SetDirectory(0);
            f->Close();
            //KolmogorovTest
            Double_t ks_signal = h_test_signal2->KolmogorovTest(h_train_signal2);
            Double_t ks_bkg = h_test_bkg2->KolmogorovTest(h_train_bkg2);
            cout<<"+++++++++ "<<cat_name[k]<<" KS test on signal "<<ks_signal<<" and bkg "<<ks_bkg<<endl;

*/
            //full path of root files containing BDT decision distribution
            TString file_name = TMVA_inputpath+cat_name[k]+"/BDTdecision_"+cat_name[k]+".root"; 
            TFile *f = new TFile(file_name,"READ");
            TH1F *h_test_signal;
            TH1F *h_test_bkg;
            TH1F *h_test_signal2;
            TH1F *h_test_bkg2;
            h_test_signal = (TH1F*)f->Get("BDTdecision_signal"+cat_name[k]);
            h_test_bkg = (TH1F*)f->Get("BDTdecision_data_obs"+cat_name[k]);
            h_test_signal2 = (TH1F*)f->Get("BDTdecision_signal"+cat_name[k]);
            h_test_bkg2 = (TH1F*)f->Get("BDTdecision_data_obs"+cat_name[k]);
            h_test_signal->SetDirectory(0);
            h_test_bkg->SetDirectory(0);
            h_test_signal2->SetDirectory(0);
            h_test_bkg2->SetDirectory(0);
            f->Close();

	    //Make up on plots
	    h_test_signal->GetXaxis()->SetRangeUser(-0.5,0.5);
	    h_test_bkg->SetLineColor(kBlack);
	    h_test_signal->SetLineColor(kRed);

            double X_min = std::min(h_test_signal->GetXaxis()->GetXmin(), h_test_signal->GetXaxis()->GetXmin());
            double X_max = std::max(h_test_signal->GetXaxis()->GetXmax(), h_test_signal->GetXaxis()->GetXmax());
	    
            //Compute cut and make colz plot
            BDTcut cut_value = Get_BDT_cut(cat_name[k], h_test_signal, h_test_bkg, true);

	    TCanvas *c1 = new TCanvas("c1","c1",150,10,990,660);
	    h_test_bkg->Draw("HISTE");
	    h_test_signal->Draw("same HISTE");
	    c1->Update();
            TLine l;
            l.DrawLine(cut_value.a,0,cut_value.a,0.1);
            l.DrawLine(cut_value.b,0,cut_value.b,0.1);

	    TLegend*leg = new TLegend(0.1,0.7,0.48,0.9);
	    leg->AddEntry(h_test_signal,cat_name[k]+"_signal","f");
	    leg->AddEntry(h_test_bkg,cat_name[k]+"_bkg","f");
	    leg->Draw();
	    c1->Update();
            c1->SaveAs(TMVA_inputpath+cat_name[k]+"/"+method+"_"+cat_name[k]+"normalizedSignal.png");

            //Drawing BDT score from scratch without signal normalization
	    TCanvas *c2 = new TCanvas("c2","c2",150,10,990,660);
	    h_test_signal2->GetXaxis()->SetRangeUser(X_min,X_max);
	    h_test_bkg2->SetLineColor(kBlack);
	    h_test_signal2->SetLineColor(kRed);
	    h_test_signal2->Scale(1/h_test_signal2->Integral());
	    h_test_bkg2->Scale(1/h_test_bkg2->Integral());
            double Y_max = std::max(h_test_signal2->GetMaximum(), h_test_bkg2->GetMaximum());
	    h_test_bkg2->Draw("HISTE");
	    h_test_bkg2->GetYaxis()->SetRangeUser(0, Y_max);
	    h_test_signal2->Draw("same HISTE");
	    c2->Update();
            l.DrawLine(cut_value.a,0,cut_value.a,Y_max);
            l.DrawLine(cut_value.b,0,cut_value.b,Y_max);
            TLatex ta(cut_value.a,0,"a");
            ta.Draw();
            TLatex tb(cut_value.b,0,"b");
            tb.Draw();

	    TLegend*leg2 = new TLegend(0.1,0.7,0.48,0.9);
	    leg2->AddEntry(h_test_signal2,cat_name[k]+"_signal","f");
	    leg2->AddEntry(h_test_bkg2,cat_name[k]+"_bkg","f");
	    leg2->Draw();
	    c2->Update();
            c2->SaveAs(TMVA_inputpath+cat_name[k]+"/"+method+"_"+cat_name[k]+".png");
     }
}
